import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Disclaimer | FinanceFlow',
  description: 'Financial and legal disclaimer for FinanceFlow tools and content.',
};

export default function DisclaimerPage() {
  return (
    <div className="section">
      <div className="container" style={{ maxWidth: '800px' }}>
        <nav className="breadcrumb" style={{ marginBottom: '2rem', fontSize: '0.875rem', color: 'var(--text-muted)' }}>
          <Link href="/">Home</Link> <span style={{ margin: '0 0.5rem' }}>›</span> <span>Disclaimer</span>
        </nav>
        
        <h1 style={{ fontSize: '2.5rem', marginBottom: '1.5rem', fontWeight: 800 }}>Disclaimer</h1>
        
        <div style={{ lineHeight: 1.8, color: 'var(--text-secondary)' }}>
          <div style={{ padding: '1.5rem', background: 'var(--bg-secondary)', borderLeft: '4px solid var(--primary)', borderRadius: '0 var(--radius-md) var(--radius-md) 0', margin: '2rem 0' }}>
            <p style={{ fontWeight: 600, color: 'var(--text-primary)', marginBottom: '0.5rem' }}>General Information Only</p>
            <p>The calculators, tools, and content provided on FinanceFlow are for general informational and educational purposes only. They do not constitute financial, investment, legal, or tax advice.</p>
          </div>

          <h2 style={{ fontSize: '1.5rem', color: 'var(--text-primary)', marginTop: '2rem', marginBottom: '1rem' }}>No Professional Advice</h2>
          <p style={{ marginBottom: '1rem' }}>FinanceFlow is not a registered investment advisor, broker/dealer, financial analyst, financial bank, securities broker or financial planner. The information on this site is provided with the understanding that we are not engaged in rendering legal, accounting, or tax professional services.</p>

          <h2 style={{ fontSize: '1.5rem', color: 'var(--text-primary)', marginTop: '2rem', marginBottom: '1rem' }}>Accuracy of Calculators</h2>
          <p style={{ marginBottom: '1rem' }}>While we strive to keep our calculators and mathematical formulas up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose.</p>
          <p style={{ marginBottom: '1rem' }}>The results generated by our calculators are estimates based on the input provided by the user and standard mathematical formulas. Actual interest rates, loan terms, and financial figures from your bank or financial institution may differ.</p>
        </div>
      </div>
    </div>
  );
}
